"""Add message_text to emoji_usage

Revision ID: 608ceca06edd
Revises: 
Create Date: 2025-08-28 11:55:57.756355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608ceca06edd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emoji_usage', sa.Column('message_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emoji_usage', 'message_text')
    # ### end Alembic commands ###